INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (14, 'AAAA-BBBB-1114', '/v3/version', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (15, 'AAAA-BBBB-1115', '/v3/iou_license', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (16, 'AAAA-BBBB-1116', '/v3/appliances', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (17, 'AAAA-BBBB-1117', '/v3/computes', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (18, 'AAAA-BBBB-1118', '/v3/computes/CCCC-AAAA-1111', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (19, 'AAAA-BBBB-1119', '/v3/projects', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (20, 'AAAA-BBBB-1121', '/v3/projects/AAAA-BBBB-1121', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (21, 'AAAA-BBBB-1122', '/v3/projects/AAAA-BBBB-1121/links', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (22, 'AAAA-BBBB-1123', '/v3/projects/AAAA-BBBB-1121/links/LLLL-AAAA-1111', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (23, 'AAAA-BBBB-1124', '/v3/projects/AAAA-BBBB-1121/links/LLLL-AAAA-1111/reset', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (24, 'AAAA-BBBB-1125', '/v3/projects/AAAA-BBBB-1121/links/LLLL-AAAA-1111/capture/start', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (25, 'AAAA-BBBB-1126', '/v3/projects/AAAA-BBBB-1121/links/LLLL-AAAA-1111/capture/stream', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (26, 'AAAA-BBBB-1127', '/v3/gns3vm', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (27, 'AAAA-BBBB-1128', '/v3/gns3vm/engines', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (28, 'AAAA-BBBB-1129', '/v3/projects/AAAA-BBBB-1121/nodes', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (29, 'AAAA-BBBB-1131', '/v3/projects/AAAA-BBBB-1121/nodes/NNNN-AAAA-1111', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (30, 'AAAA-BBBB-1132', '/v3/projects/AAAA-BBBB-1121/nodes/NNNN-AAAA-1111/start', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (31, 'AAAA-BBBB-1133', '/v3/projects/AAAA-BBBB-1121/nodes/NNNN-AAAA-1111/duplicate', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (32, 'AAAA-BBBB-1134', '/v3/projects/AAAA-BBBB-1121/nodes/NNNN-AAAA-1111/links', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (33, 'AAAA-BBBB-1135', '/v3/projects/AAAA-BBBB-1121/nodes/NNNN-AAAA-1111/files/FFFF-AAAA-1111', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (34, 'AAAA-BBBB-1136', '/v3/projects/AAAA-BBBB-1121/nodes/console/reset', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (35, 'AAAA-BBBB-1137', '/v3/projects/AAAA-BBBB-1121/nodes/NNNN-AAAA-1111/console/reset', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (36, 'AAAA-BBBB-1138', '/v3/notification', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (37, 'AAAA-BBBB-1139', '/v3/projects/load', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (38, 'AAAA-BBBB-1141', '/v3/projects/AAAA-BBBB-1121/stats', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (39, 'AAAA-BBBB-1142', '/v3/projects/AAAA-BBBB-1121/export', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (40, 'AAAA-BBBB-1143', '/v3/projects/AAAA-BBBB-1121/duplicate', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (41, 'AAAA-BBBB-1144', '/v3/projects/AAAA-BBBB-1121/snapshots', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (42, 'AAAA-BBBB-1145', '/v3/projects/AAAA-BBBB-1122/snapshots/SSSS-AAAA-1111', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (43, 'AAAA-BBBB-1146', '/v3/symbols', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (44, 'AAAA-BBBB-1147', '/v3/symbols/XXXX-AAAA-1111/raw', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (45, 'AAAA-BBBB-1148', '/v3/symbols/default_symbols', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (46, 'AAAA-BBBB-1149', '/v3/templates', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (47, 'AAAA-BBBB-1151', '/v3/templates/TTTT-AAAA-1111', 'ENDPOINT');
INSERT INTO RESOURCES (RSC_ID, UUID, RSC_TYPE) VALUES (48, 'AAAA-BBBB-1152', '/v3/templates/TTTT-AAAA-1111/duplicate', 'ENDPOINT');




INSERT INTO RESOURCES_GROUP (RSC_GROUP_ID, UUID, NAME) VALUES (6, 'GROUP-AAAA-1116', 'tous les computes');
INSERT INTO RESOURCES_GROUP (RSC_GROUP_ID, UUID, NAME) VALUES (7, 'GROUP-AAAA-1116', 'action pour application');


INSERT INTO USERS (USER_ID, PASSWORD, RESSOURCE_ID) VALUES (1, 'NIELS', 'unmotdepassehaché4');


INSERT INTO PERMISSIONS (PERM_ID, NAME) VALUES (7, 'NODE_POWER_MGNT');
INSERT INTO PERMISSIONS (PERM_ID, NAME) VALUES (8, 'NODE_SNAPSHOT');
INSERT INTO PERMISSIONS (PERM_ID, NAME) VALUES (9, 'LINK_CAPTURE');
INSERT INTO PERMISSIONS (PERM_ID, NAME) VALUES (10, 'LINK_FILTER');


INSERT INTO PERMISSIONS_GROUPS (PERM_GROUP_ID, NAME) VALUES (5, 'TEMPLATEADMIN');
INSERT INTO PERMISSIONS_GROUPS (PERM_GROUP_ID, NAME) VALUES (6, 'IMAGEADMIN');
INSERT INTO PERMISSIONS_GROUPS (PERM_GROUP_ID, NAME) VALUES (4, 'USERADMIN');

INSERT INTO PERMISSIONS_GROUP_MEMBERS (PERMISSION_MEMBER_ID, PERMISSIONS_GROUP_ID, PERMISSION_ID) VALUES (10, 4, 1);


